# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyGoogleMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyGoogleMap
pod 'GoogleMaps', '~> 7.3'
pod 'GooglePlaces', '~> 7.3'
end
